// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwI__UWFkvy543SOj1l6_9SQyP9gD3s0I',
    appId: '1:304087169003:web:7f8133a68fb8740006cbae',
    messagingSenderId: '304087169003',
    projectId: 'messenger-87793',
    authDomain: 'messenger-87793.firebaseapp.com',
    storageBucket: 'messenger-87793.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCked3-DSz1IFA1hyYgXhjoD7YbS3-aNAA',
    appId: '1:304087169003:android:1bf3bddc1bf880c406cbae',
    messagingSenderId: '304087169003',
    projectId: 'messenger-87793',
    storageBucket: 'messenger-87793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo8Cbs967Ug4Kzr-aFHhytM_3X0JBW5So',
    appId: '1:304087169003:ios:4931887771fa132d06cbae',
    messagingSenderId: '304087169003',
    projectId: 'messenger-87793',
    storageBucket: 'messenger-87793.appspot.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo8Cbs967Ug4Kzr-aFHhytM_3X0JBW5So',
    appId: '1:304087169003:ios:7b4fcb1fe375403f06cbae',
    messagingSenderId: '304087169003',
    projectId: 'messenger-87793',
    storageBucket: 'messenger-87793.appspot.com',
    iosBundleId: 'com.example.messenger.RunnerTests',
  );
}
